# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {}".format(planet,diameter))

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd


In [15]:
d = {'col1': [1,2,3], 'col2': [4,5,6]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     4
1     2     5
2     3     6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [16]:
import pandas as pd
cal = pd.date_range(start ='1-1-2023',end ='02-10-2023', freq ='12H')
print(cal)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 12:00:00',
               '2023-01-02 00:00:00', '2023-01-02 12:00:00',
               '2023-01-03 00:00:00', '2023-01-03 12:00:00',
               '2023-01-04 00:00:00', '2023-01-04 12:00:00',
               '2023-01-05 00:00:00', '2023-01-05 12:00:00',
               '2023-01-06 00:00:00', '2023-01-06 12:00:00',
               '2023-01-07 00:00:00', '2023-01-07 12:00:00',
               '2023-01-08 00:00:00', '2023-01-08 12:00:00',
               '2023-01-09 00:00:00', '2023-01-09 12:00:00',
               '2023-01-10 00:00:00', '2023-01-10 12:00:00',
               '2023-01-11 00:00:00', '2023-01-11 12:00:00',
               '2023-01-12 00:00:00', '2023-01-12 12:00:00',
               '2023-01-13 00:00:00', '2023-01-13 12:00:00',
               '2023-01-14 00:00:00', '2023-01-14 12:00:00',
               '2023-01-15 00:00:00', '2023-01-15 12:00:00',
               '2023-01-16 00:00:00', '2023-01-16 12:00:00',
               '2023-01-

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [17]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:
df = pd.DataFrame([lists])
df.columns =['col1','col2','col3']
print(df)

           col1          col2          col3
0  [1, aaa, 22]  [2, bbb, 25]  [3, ccc, 24]
